name: manage-azure-policy-ebb192ab
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**'
#      - .github/workflows/manage-azure-policy-ebb192ab.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ebb192ab}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**
